### ISSUE TITLE
프림 필터(남의 필터)

### ISSUE THREAD

**Issue by JeaSungLEE** [mash-up-kr/Pream-iOS#15]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/13097922/52686900-01e51880-2f93-11e9-9193-153632cc7bbb.png">

**Comment by gaonK** [comment]
#17 #20 #24

**Comment by JeaSungLEE** [comment]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/13097922/52989079-30f10380-3445-11e9-94fe-46abcb56282a.png">
